baseURL: "https://genomes.scilifelab.se/"
languageCode: "en-us"
title: "Swedish Reference Genome Portal, hosted by SciLifeLab"
buildFuture: true

outputs:
  home:
    - HTML
    - JSON

outputFormats:
  JSON:
    mediaType: "application/json"
    baseName: "species_catalog"
    isPlainText: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 3
    endLevel: 4
    ordered: false

menus:
  main:
  - name: About
    pageRef: /about
    weight: 1
  - name: Contact
    pageRef: /contact
    weight: 2
  - name: FAQ
    pageRef: /faqs
    weight: 3
  - name: Cite us
    pageRef: /citation
    weight: 4

  sub:
  - name: Home
    pageRef: /
    weight: 1
  - name: Contribute
    pageRef: /contribute
    weight: 2
  - name: User guide
    pageRef: /user-guide
    weight: 3
  - name: Glossary
    pageRef: /glossary
    weight: 4

  mobile:
    - name: Home
      pageRef: /
      weight: 1
    - name: About
      pageRef: /about
      weight: 2
    - name: Contact
      pageRef: /contact
      weight: 3
    - name: Contribute
      pageRef: /contribute
      weight: 4
    - name: User guide
      pageRef: /user-guide
      weight: 5
    - name: Glossary
      pageRef: /glossary
      weight: 6
    - name: Cite us
      pageRef: /citation
      weight: 7
    - name: FAQ
      pageRef: /faqs
      weight: 8
