baseURL: "https://genomes.scilifelab.se/"
languageCode: "en-us"
title: "Swedish Reference Genome Portal, hosted by SciLifeLab"
buildFuture: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 3
    endLevel: 4
    ordered: false

menus:
  main:
  - name: Home
    pageRef: /
    weight: 1
  - name: About
    pageRef: /about
    weight: 2
  - name: Contact
    pageRef: /contact
    weight: 3
  - name: Contribute
    pageRef: /contribute
    weight: 4

  sub:
  - name: Cite us
    pageRef: /citation
    weight: 1
  - name: Glossary
    pageRef: /glossary
    weight: 2
  - name: User guide
    pageRef: /user-guide
    weight: 3
