baseURL: "https://swedgene.se/"
languageCode: "en-us"
title: "Swedish national genome portal, hosted by SciLifeLab"
buildFuture: true
params:
  title: "Swedish national genome portal, hosted by SciLifeLab"
  description: "Swedish national genome portal, hosted by SciLifeLab"

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 3
    endLevel: 4
    ordered: false

menus:
  main:
  - name: Home
    pageRef: /
    weight: 1
  - name: Add a genome project
    pageRef: /add_genome
    weight: 2
  - name: About
    pageRef: /about
    weight: 3
  - name: Contact
    pageRef: /contact
    weight: 4
