repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-json
    exclude: ^hugo/layouts/index\.json\.json$
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
    files: 'hugo/'
    exclude: '^(hugo/static/|hugo/content/)'
  - id: trailing-whitespace
    files: '^(hugo/|scripts/|tests/)'
    exclude: 'hugo/static/'

# for markdown
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.39.0
  hooks:
  - id: markdownlint-fix
    args: ['--config', '.github/.markdownlint.yaml']
    files: '^hugo/content/.*'

# for python
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      files: '^(scripts|playwright)/.*'
    # Run the formatter.
    - id: ruff-format
      files: '^(scripts|playwright)/.*'

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
    - id: shellcheck
      args: ["-f", "gcc", "-S", "warning"]
      files: 'scripts/.*'
      exclude: 'scripts/data_stewardship'
      types_or: [shell, bash]
