- name: ASM1142v1
  accession: GCF_000011425.1
  url: "https://ftp.ncbi.nlm.nih.gov/genomes/refseq/fungi/Aspergillus_nidulans/latest_assembly_versions/GCF_000011425.1_ASM1142v1/GCF_000011425.1_ASM1142v1_genomic.fna.gz"
  organism: "Aspergillus nidulans"
  tracks:
    - name: "Protein coding genes"
      url: "https://ftp.ncbi.nlm.nih.gov/genomes/refseq/fungi/Aspergillus_nidulans/latest_assembly_versions/GCF_000011425.1_ASM1142v1/GCF_000011425.1_ASM1142v1_genomic.gff.gz"
  hubs:
    - name: "UCSC asembly hub"
      url: "https://hgdownload.soe.ucsc.edu/hubs/GCF/000/011/425/GCF_000011425.1/hub.txt"
- name: Ch_v2.0.2
  organism: "Clupea harengus"
  accession: GCF_900700415.2
  url: "https://hgdownload.soe.ucsc.edu/hubs/GCF/900/700/415/GCF_900700415.2/GCF_900700415.2.2bit"
  tracks:
    - name: "Protein coding genes"
      url: "https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_other/Clupea_harengus/latest_assembly_versions/GCF_900700415.2_Ch_v2.0.2/GCF_900700415.2_Ch_v2.0.2_genomic.gff.gz"
  hubs:
    - name: "UCSC Assembly hub"
      url: "https://hgdownload.soe.ucsc.edu/hubs/GCF/900/700/415/GCF_900700415.2/hub.txt"    
      
