organism: "Bufotes viridis"
assembly:
  name: Bufotes_viridis_n_2023_12
  displayName: "B. viridis genome assembly GCA_963931945.1"
  accession: GCA_963931945.1
  url: "ftp://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/caw/CAWYQA01.fasta.gz"
# tracks:
#   - name: "Protein-coding genes"
#     url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/963/931/945/GCA_963931945.1_Bufotes_viridis_n_2023_12/GCA_963931945.1_Bufotes_viridis_n_2023_12_genomic.gff.gz

###NOTE: Due to the size of the chromosomes in the assembly, this GFF file requires a .csi index
### first, uncomment the protein-coding genes track and run
##./scripts/dockermake -t local SPECIES=bufotes_viridis
### The files are now downloaded, but the process exits on with a tbi error. Comment the the protein-coding genes track and run
##./scripts/dockermake -t local SPECIES=bufotes_viridis
## This creates data/bufotes_viridis/config.json. Then manualy index the track and add it to the config:
##tabix -p gff --csi data/bufotes_viridis/GCA_963931945.1_Bufotes_viridis_n_2023_12_genomic.gff.bgz
##jbrowse add-track --load inPlace GCA_963931945.1_Bufotes_viridis_n_2023_12_genomic.gff.bgz --name="Protein-coding genes" --assemblyNames="Bufotes_viridis_n_2023_12" --target data/bufotes_viridis/config.json --indexFile GCA_963931945.1_Bufotes_viridis_n_2023_12_genomic.gff.bgz.csi