organism: "Parnassius mnemosyne"
assembly:
  name: Parnassius_mnemosyne_n_2023_11
  displayName: "P. mnemosyne genome assembly GCA_963668995.1"
  accession: GCA_963668995.1
  url: "https://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/cav/CAVLGL01.fasta.gz"
  # Temp storage for alias file. 
  aliases: "https://raw.githubusercontent.com/ScilifelabDataCentre/genome-portal/main/scripts/data_stewardship/alias_files_temp_storage/CAVLGL01.fna.alias"

tracks:
  - name: "Protein-coding genes"
    #trackDescription: "Annotation of protein-coding genes, original version that was submitted to ENA"
    url: "https://figshare.scilifelab.se/ndownloader/files/47209624"
    fileName: "pmne_functional_edit1.gff.gz"
  - name: "Illumina RNAseq transcript assembly (thorax muscle tissue)"
    url: "https://figshare.scilifelab.se/ndownloader/files/47209648"
    fileName: "pmne_Illumina_RNAseq_StringTie_sorted-transcripts_match.gff.gz"
  - name: "Non-coding RNA (ncRNA) genes"
    url: "https://figshare.scilifelab.se/ndownloader/files/47209660"
    fileName: "pmne_ncRNAs.gff.gz"
  - name: "tRNA genes and putative pseudogenes"
    url: "https://figshare.scilifelab.se/ndownloader/files/47209663"
    fileName: "pmne_tRNAs_and_pseudogenes.gff.gz"