organism: "Parnassius mnemosyne"
assembly:
  name: Parnassius_mnemosyne_n_2023_11
  accession: GCA_963668995.1
  url: "https://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/cav/CAVLGL01.fasta.gz"
  # Temp storage for alias file. At a later stage it would be more FAIR to store it in a another repo (such as SLL Figshare) where it can get a PID.
  aliases: "https://raw.githubusercontent.com/ScilifelabDataCentre/swedgene/main/scripts/data_stewardship/alias_files_temp_storage/CAVLGL01.fna.alias"

tracks:
  # - name: "Protein coding genes (NCBI version)"
  #   #trackDescription: "Annotation of protein coding genes, processed by NCBI"
  #   url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/963/668/995/GCA_963668995.1_Parnassius_mnemosyne_n_2023_11/GCA_963668995.1_Parnassius_mnemosyne_n_2023_11_genomic.gff.gz"
  #   #defaultSession: no
  - name: "Protein coding genes"
    #trackDescription: "Annotation of protein coding genes, original version that was submitted to ENA"
    url: "https://figshare.scilifelab.se/ndownloader/files/47209624"
    fileName: "pmne_functional_edit1.gff.gz"
    #defaultSession: yes
  - name: "Illumina RNAseq transcript assembly (thorax muscle tissue)"
    url: "https://figshare.scilifelab.se/ndownloader/files/47209648"
    fileName: "pmne_Illumina_RNAseq_StringTie_sorted-transcripts_match.gff.gz"
    #defaultSession: yes
  - name: "Non-coding RNA (ncRNA) genes"
    url: "https://figshare.scilifelab.se/ndownloader/files/47209660"
    fileName: "pmne_ncRNAs.gff.gz"
    #defaultSession: no
  - name: "tRNA genes and putative pseudogenes"
    url: "https://figshare.scilifelab.se/ndownloader/files/47209663"
    fileName: "pmne_tRNAs_and_pseudogenes.gff.gz"
    #defaultSession: no

# ### Notes on mitochondrial assembly and tracks. To remain commented until a decision on how to handle secondary assemblies is made.
# assembly:
#   name: "Parnassius mnemosyne genome assembly, organelle: mitochondrion"
#   accession: OZ075093.1
#   url: "https://www.ebi.ac.uk/ena/browser/api/fasta/OZ075093.1?download=true&gzip=true"
#   fileName: "OZ075093.1.fasta.gz"
#   #aliases: ""
# tracks:
#   - name: "Mitochondrial genes"
#     trackDescription: "Annotation of protein coding genes in the mitochondrion"
#     url: "https://figshare.scilifelab.se/ndownloader/files/47209654"
#     fileName: "pmne_mtdna.gff.gz"
#     #defaultSession: yes