assembly_fields:
  description:
    - ["name", "Assembly Name"]
    - ["type", "Assembly Type"]
    - ["level", "Assembly Level"]
    - ["repr", "Assembly Representation"]
    - ["accession"]
  stats:
    - ["length",  "Assembly length (Mbp)"]
    - ["gc", "GC %"]
    - ["contig", "Contig #" ]
    - ["contig_n50", "Contig N50 (Mbp)" ]
    - ["contig_l50"]
    - ["contig_n90", "Contig N90 (Mbp)" ]
    - ["contig_l90"]
    - ["scaffold", "Scaffold #"]
    - ["scaffold_n50", "Scaffold N50 (Mbp)"]
    - ["scaffold_l50"]
    - ["scaffold_n90", "Scaffold N90 (Mbp)"]
    - ["scaffold_l90"]
    - ["scaffold_gt_10", "Scaffolds >= 10 kb"]
    - ["busco", "BUSCO %"]
  annotation:
    - ["gene_cnt", "Gene #"]
    - ["transcript_cnt", "Transcript #"]
    - ["exons_avg", "Avg exons per transcript"]
    - ["gene_length_avg","Avg gene length (bp)"]
    - ["transcript_length_avg", "Avg transcript length (bp)"]
    - ["exon_length_avg", "Avg exon length (bp)"]
    - ["intron_length_avg", "Avg intron length (bp)"]
