organism: Blastobotrys illinoisensis
assembly:
  name: BILLI_YB1343_PB
  displayName: B. illinoisensis genome assembly GCA_965113335.1
  accession: GCA_965113335.1
  url: https://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/cbc/CBCOUN01.fasta.gz
  fileName: CBCOUN01.fasta.gz
tracks:
- name: Protein-coding genes
  url: https://figshare.scilifelab.se/ndownloader/files/53044784
  fileName: billinoisensis_annotation.gff
