organism: "Linum trigynum"
assembly:
  name: Ltrigynum_genome
  accession: GCA_964030455.1
  # The following url points to the original ENA upload of the assembly. Interestingly, due to the metadata for this ENA submission, 
  # this file only contains the unplaced scaffolds, and not the ten chromosome sequences. Will circumvent this for now by using the NCBI mirror instead.
  #url: "https://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/cax/CAXIPQ01.fasta.gz"
  url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/964/030/455/GCA_964030455.1_Ltrigynum_genome/GCA_964030455.1_Ltrigynum_genome_genomic.fna.gz"
  # Temp storage for alias file. At a later stage it would be more FAIR to store it in a another repo (such as SLL Figshare) where it can get a PID.
  aliases: "https://raw.githubusercontent.com/ScilifelabDataCentre/swedgene/main/scripts/data_stewardship/alias_files_temp_storage/GCA_964030455.1_Ltrigynum_genome_genomic.fna.alias"
tracks:
  - name: "Protein coding genes"
  # Note: this annotation file is compressed with zip, not gzip. 
  # Note2; It only contains annotations for the chromosomes, not the unplaced scaffolds.
    url: "https://figshare.scilifelab.se/ndownloader/files/44990356"
    fileName: "Ltrigynum_v1_genes.gtf.zip"