organism: "Linum trigynum"
assembly:
  name: Ltrigynum_genome
  displayName: "Linum trigynum genome assembly"
  accession: GCA_964030455.1
  # The following url points to the original ENA upload of the assembly. Interestingly, due to the metadata for this ENA submission, 
  # this file only contains the unplaced scaffolds, and not the ten chromosome sequences. Will circumvent this for now by using the NCBI mirror instead.
  #url: "https://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/cax/CAXIPQ01.fasta.gz"
  url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/964/030/455/GCA_964030455.1_Ltrigynum_genome/GCA_964030455.1_Ltrigynum_genome_genomic.fna.gz"
  # Temp storage for alias file. At a later stage it would be more FAIR to store it in a another repo (such as SLL Figshare) where it can get a PID.
  aliases: "https://raw.githubusercontent.com/ScilifelabDataCentre/genome-portal/main/scripts/data_stewardship/alias_files_temp_storage/GCA_964030455.1_Ltrigynum_genome_genomic.fna.alias"
tracks:
  - name: "Protein coding genes"
    url: "https://figshare.scilifelab.se/ndownloader/files/48853129"
    fileName: "Ltrigynum_v1_genes.gff.gz"
  - name: "Repeats"
    url: "https://figshare.scilifelab.se/ndownloader/files/48879658"
    fileName: "L_trigynum_v1_rep.bed.gz"
  - name: Ltri_pop01_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074032"
    fileName: "Ltri_pop01_TD.bed.gz"
    addTrack: false
  - name: "Ltri_pop03_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074035"
    fileName: "Ltri_pop03_TD.bed.gz"
    addTrack: false
  - name: "Ltri_pop04_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074038"
    fileName: "Ltri_pop04_TD.bed.gz"
    addTrack: false
  - name: "Ltri_pop06_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074041"
    fileName: "Ltri_pop06_TD.bed.gz"
    addTrack: false
  - name: "Ltri_pop07_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074044"
    fileName: "Ltri_pop07_TD.bed.gz"
    addTrack: false
  - name: "Ltri_pop08_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074047"
    fileName: "Ltri_pop08_TD.bed.gz"
    addTrack: false
  - name: "Ltri_pop10_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074050"
    fileName: "Ltri_pop10_TD.bed.gz"
    addTrack: false
  - name: "Ltri_pop11_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074053"
    fileName: "Ltri_pop11_TD.bed.gz"
    addTrack: false
  - name: "Ltri_pop01_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074059"
    fileName: "Ltri_pop01_Pi.bed.gz"
    addTrack: false
  - name: "Ltri_pop03_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074062"
    fileName: "Ltri_pop03_Pi.bed.gz"
    addTrack: false
  - name: "Ltri_pop04_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074065"
    fileName: "Ltri_pop04_Pi.bed.gz"
    addTrack: false
  - name: Ltri_pop06_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074068"
    fileName: "Ltri_pop06_Pi.bed.gz"
    addTrack: false
  - name: "Ltri_pop07_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074071"
    fileName: "Ltri_pop07_Pi.bed.gz"
    addTrack: false
  - name: "Ltri_pop08_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074074"
    fileName: "Ltri_pop08_Pi.bed.gz"
    addTrack: false
  - name: "Ltri_pop10_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074077"
    fileName: "Ltri_pop10_Pi.bed.gz"
    addTrack: false
  - name: "Ltri_pop11_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074080"
    fileName: "Ltri_pop11_Pi.bed.gz"
    addTrack: false

  # - name: "Ltri_pop01_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006102"
  #   fileName: "Ltri_pop01_TD.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop03_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006105"
  #   fileName: "Ltri_pop03_TD.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop04_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006108"
  #   fileName: "Ltri_pop04_TD.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop06_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006111"
  #   fileName: "Ltri_pop06_TD.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop07_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006117"
  #   fileName: "Ltri_pop07_TD.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop08_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006120"
  #   fileName: "Ltri_pop08_TD.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop10_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006123"
  #   fileName: "Ltri_pop10_TD.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop11_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006126"
  #   fileName: "Ltri_pop11_TD.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop01_Pi"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49005187"
  #   fileName: "Ltri_pop01_Pi.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop03_Pi"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49005193"
  #   fileName: "Ltri_pop03_Pi.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop04_Pi"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49005196"
  #   fileName: "Ltri_pop04_Pi.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop06_Pi"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49005199"
  #   fileName: "Ltri_pop06_Pi.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop07_Pi"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49005202"
  #   fileName: "Ltri_pop07_Pi.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop08_Pi"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49005208"
  #   fileName: "Ltri_pop08_Pi.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop10_Pi"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49005211"
  #   fileName: "Ltri_pop10_Pi.bed.zip"
  #   addTrack: false
  # - name: "Ltri_pop11_Pi"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49005214"
  #   fileName: "Ltri_pop11_Pi.bed.zip"
  #   addTrack: false
