#!/bin/bash

help() {
  echo "\
Serve Genome Portal in a Docker container

Usage: dockerserve [-h] [-t TAG] [-p PORT] [-d] [-n]

Options:
  -h            Display this help message and exit
  -t TAG        Docker image tag. Default: local
  -p PORT       Host port. Default: 8080
  -d            Use Hugo development server (formerly --dev)
  -n            Dry run

In dev mode, Hugo (genome-portal-hugo) only serves hugo/, and a small
nginx proxy (genome-portal) sits in front of it: It serves the genome data (data/)
directly. This means both Hugo content changes and data changes (from re-running `dockermake`) are reflected in the browser immediately,

Legacy SWG-prefixed environment variables are still supported
(but command line counterparts take precedence). For example, to serve on
port 8000 with the 'latest' tag, the following are equivalent:

  SWG_PORT=8000 SWG_TAG=latest ./scripts/dockerserve

  ./scripts/dockerserve -t latest -p 8000
"
}

main() {
  CWD="$(git rev-parse --show-toplevel)"
  readonly CWD

  local image="${SWG_IMAGE:-ghcr.io/scilifelabdatacentre/swg-hugo-site}" \
        tag="${SWG_TAG:-local}" \
        port="${SWG_PORT:-8080}" \
        datadir="${SWG_DATA_DIR:-data}" \
        hugo_image="${SWG_HUGO_IMAGE:=hugomods/hugo}" \
        hugo_tag="${SWG_HUGO_TAG:=std-base-0.138.0}" \
        proxy_image="${SWG_PROXY_IMAGE:=nginxinc/nginx-unprivileged:stable-alpine}" \
        dev=0 \
        container_name=genome-portal \
        dry_run=0

  # This network used in dev mode so the hugo container and the proxy container can communicate
  local hugo_container_name="${container_name}-hugo" \
        network_name="genome-portal-dev"

  while getopts t:p:dhn opt; do
    case "${opt}" in
      t) tag="${OPTARG}" ;;
      p) port="${OPTARG}" ;;
      d) dev=1 ;;
      h) help; exit 0 ;;
      n) dry_run=1 ;;
      \?) >&2 help; exit 1 ;;
    esac
  done

  cid="$(docker ps -qaf "name=^/${container_name}$" -f "name=^/${hugo_container_name}$")"
  if [[ -n "${cid}" ]]; then
    cat <<-EOF
	Name '${container_name}' or '${hugo_container_name}' already taken by container(s):
	${cid}
	To stop and remove:
	  docker rm -f ${cid}
EOF
    return 1
  fi

  if run 2>/tmp/dockerserve.log && ! ((dry_run)); then
    if ((dev)); then
      cat <<-EOF
	- Web server is running in containers "${container_name}" (proxy) and "${hugo_container_name}" (Hugo dev server).
	- Site can be visited at http://localhost:${port}

	To shut down:
	  docker rm -f "${container_name}" "${hugo_container_name}"
EOF
    else
      cat <<-EOF
	- Web server is running in container "${container_name}".
	- Site can be visited at http://localhost:${port}

	To shut down:
	  docker rm -f "${container_name}"
EOF
    fi
  else
    cat /tmp/dockerserve.log
  fi
}

run() {
  run_cmd="docker run"
  network_cmd="docker network create"
  ((dry_run)) && run_cmd="echo ${run_cmd}"
  ((dry_run)) && network_cmd="echo ${network_cmd}"

  if ((dev)); then
    ${network_cmd} "${network_name}" >/dev/null 2>&1 || true

    ${run_cmd} --rm -d  \
           --network "${network_name}" \
           -v "${CWD}/hugo":"/src" \
           --name "${hugo_container_name}" \
           "${hugo_image}:${hugo_tag}" hugo server --bind 0.0.0.0 \
    && ${run_cmd} --rm -d  \
           --network "${network_name}" \
           -p "${port}":8080 \
           -v "${CWD}/${datadir}":"/usr/share/nginx/html/data":ro \
           -v "${CWD}/docker/nginx-dev-proxy.conf":"/etc/nginx/conf.d/default.conf":ro \
           --name "${container_name}" \
           "${proxy_image}" \
    || { docker rm -f "${hugo_container_name}" >/dev/null 2>&1; return 1; }
  else
    ${run_cmd} -d  \
           -p "${port}":8080 \
           -v "${CWD}/${datadir}":"/usr/share/nginx/html/data" \
           --name "${container_name}" \
           "${image}:${tag}"
  fi
}

main "$@"
