organism: "Littorina saxatilis"
assembly:
  name: US_GU_Lsax_2.0
  displayName: "L. saxatilis genome assembly GCA_037325665.1"
  accession: "GCA_037325665.1"
  # Use the NCBI version of the assembly to get a user-friendly sorting in the JBrowse dropdown by default
  # (the 17 chroms on top of the list and the 4000+ unplaced scaffolds below)
  url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/037/325/665/GCA_037325665.1_US_GU_Lsax_2.0/GCA_037325665.1_US_GU_Lsax_2.0_genomic.fna.gz"
tracks:
  - name: "Protein-coding genes"
    url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/037/325/665/GCA_037325665.1_US_GU_Lsax_2.0/GCA_037325665.1_US_GU_Lsax_2.0_genomic.gff.gz"