organism: "Linum tenue"
assembly:
  name: Linum_tenue_thrum_v1
  displayName: "L. tenue genome assembly GCA_946122785.1"
  accession: GCA_946122785.1
  # The following url points to the original ENA upload of the assembly. It will require an alias file to be able to load the protein coding genes track
  url: "https://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/cam/CAMGYJ01.fasta.gz"
tracks:
  - name: "Protein-coding genes"
    url: "https://figshare.scilifelab.se/ndownloader/files/45076090"
    fileName: "ltenue_v1_genes.gff.zip"
    addTrack: false 
  - name: "Repeats"
    url: "https://figshare.scilifelab.se/ndownloader/files/48879751"
    fileName: "L_tenue_v1_rep.bed.gz"
  - name: "Lten_pop06_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073936"
    fileName: "Lten_pop06_TD.bed.gz"
    addTrack: false  
  - name: "Lten_pop08_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073939"
    fileName: "Lten_pop08_TD.bed.gz"
    addTrack: false  
  - name: "Lten_pop17_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073942"
    fileName: "Lten_pop17_TD.bed.gz"
    addTrack: false  
  - name: "Lten_pop21_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073945"
    fileName: "Lten_pop21_TD.bed.gz"
    addTrack: false  
  - name: "Lten_pop23_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073951"
    fileName: "Lten_pop23_TD.bed.gz"
    addTrack: false  
  - name: "Lten_pop26_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073954"
    fileName: "Lten_pop26_TD.bed.gz"
    addTrack: false  
  - name: "Lten_pop32_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073957"
    fileName: "Lten_pop32_TD.bed.gz"
    addTrack: false  
  - name: "Lten_pop34_TD.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073960"
    fileName: "Lten_pop34_TD.bed.gz"
    addTrack: false  
  - name: "Lten_pop06_Pi"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073987"
    fileName: "Lten_pop06_Pi.bed.gz"
    addTrack: false  
  - name: "Lten_pop08_Pi"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073990"
    fileName: "Lten_pop08_Pi.bed.gz"
    addTrack: false  
  - name: "Lten_pop17_Pi"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073993"
    fileName: "Lten_pop17_Pi.bed.gz"
    addTrack: false  
  - name: "Lten_pop21_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50073999"
    fileName: "Lten_pop21_Pi.bed.gz"
    addTrack: false  
  - name: "Lten_pop23_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074002"
    fileName: "Lten_pop23_Pi.bed.gz"
    addTrack: false  
  - name: "Lten_pop26_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074005"
    fileName: "Lten_pop26_Pi.bed.gz"
    addTrack: false  
  - name: "Lten_pop32_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074008"
    fileName: "Lten_pop32_Pi.bed.gz"
    addTrack: false  
  - name: "Lten_pop34_Pi.bed"
    url: "https://figshare.scilifelab.se/ndownloader/files/50074011"
    fileName: "Lten_pop34_Pi.bed.gz"
    addTrack: false  




  # - name: "Lten_pop06_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006876"
  #   fileName: "Lten_pop06_TD.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop08_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006879"
  #   fileName: "Lten_pop08_TD.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop17_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006882"
  #   fileName: "Lten_pop17_TD.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop21_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006888"
  #   fileName: "Lten_pop21_TD.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop23_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006891"
  #   fileName: "Lten_pop23_TD.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop26_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49007380"
  #   fileName: "Lten_pop26_TD.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop32_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006918"
  #   fileName: "Lten_pop32_TD.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop34_TD"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006924"
  #   fileName: "Lten_pop34_TD.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop06_PI"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006264"
  #   fileName: "Lten_pop06_Pi.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop08_PI"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006267"
  #   fileName: "Lten_pop08_Pi.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop17_PI"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006270"
  #   fileName: "Lten_pop17_Pi.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop21_PI"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006273"
  #   fileName: "Lten_pop21_Pi.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop23_PI"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006282"
  #   fileName: "Lten_pop23_Pi.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop26_PI"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006285"
  #   fileName: "Lten_pop26_Pi.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop32_PI"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006297"
  #   fileName: "Lten_pop32_Pi.bed.zip"
  #   addTrack: false
  # - name: "Lten_pop34_PI"
  #   url: "https://figshare.scilifelab.se/ndownloader/files/49006300"
  #   fileName: "Lten_pop34_Pi.bed.zip"
  #   addTrack: false



  
