organism: "Linum tenue"
assembly:
  name: Linum_tenue_thrum_v1
  accession: GCA_946122785.1
  # The following url points to the original ENA upload of the assembly. It will require an alias file to be able to load the protein coding genes track
  url: "https://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/cam/CAMGYJ01.fasta.gz"
tracks:
  - name: "Protein coding genes"
  # Note: this annotation file is compressed with zip, not gzip
    url: "https://figshare.scilifelab.se/ndownloader/files/45076090"
    fileName: "ltenue_v1_genes.gff.zip"