name: Build and push Hugo site image to GitHub Container Registry
on:
  push:
    branches:
      - prod # Branch to be deployed in production, through builds tagged prod
      - main # Branch to be deployed in development, through builds tagged dev
      
  # workflow_dispatch can be used on feature branch to test the site on dev instance
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker tag for the image, default is dev'
        required: false
        default: 'dev'

jobs:
  push-to-container-registry:
    if: github.repository == 'ScilifelabDataCentre/swedgene'  
    name: Build and push Hugo site Docker image to GitHub Container Registry

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
        
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set Docker tag
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.docker_tag }}" >> $GITHUB_OUTPUT;
          elif [ "${{ github.ref }}" == "refs/heads/prod" ]; then
            echo "tag=prod" >> $GITHUB_OUTPUT;
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=dev" >> $GITHUB_OUTPUT;
          fi

      - name: Create Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/scilifelabdatacentre/swg-hugo-site
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: ./docker/hugo.dockerfile
          tags: ghcr.io/scilifelabdatacentre/swg-hugo-site:${{ steps.set-tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}