name: Build hugo site and test site with Lighthouse CI
on:
  push:
    branches:
      - prod # Branch to be deployed in production, through builds tagged prod
      - main # Branch to be deployed in development, through builds tagged dev 
    paths:
      - 'hugo/**'
  
  pull_request:
    branches:
      - prod # Branch to be deployed in production, through builds tagged prod
      - main # Branch to be deployed in development, through builds tagged dev 
    paths:
      - 'hugo/**'

jobs:
  lighthouse_ci:
    name: Test site with Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.128.2'
        
      - name: Build Hugo
        run: |
          cd hugo
          hugo --minify --gc 

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun --config=.github/lighthouserc.json
