name: Run pre-commit checks 

on:
  push:
    branches:
      - main
      - develop
      - add-precommit-ghactions # TODO - temp for testing 
  pull_request:
    branches:
      - main
      - develop

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pre-commit==3.7.0
    - name: Run pre-commit
      run: pre-commit run --all-files