name: Run pre-commit checks 

on:
  push:
    branches:
      - prod # Branch to be deployed in production, through builds tagged prod
      - main # Branch to be deployed in development, through builds tagged dev 
  pull_request:
    branches:
      - prod # Branch to be deployed in production, through builds tagged prod
      - main # Branch to be deployed in development, through builds tagged dev 

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pre-commit==3.7.0
    - name: Run pre-commit
      run: pre-commit run --all-files