name: Build and push both docker images to the GitHub Container Registry
on:
  push:
    # Branch to be used in development, builds images tagged as "dev"
    branches:
      - main 
    paths-ignore:
      - 'README.md'
  
  # Triggered when a release is published - builds images tagged as "prod"
  release:
    types: [published]

  # workflow_dispatch can be used on feature branch to test the site on dev instance
  # Or fix a bug on a release branch
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker tag for the image, default is dev. Use prod for a release branch fix'
        required: false
        default: 'dev'

jobs:
  push-to-container-registry:
    if: github.repository == 'ScilifelabDataCentre/genome-portal'  
    name: Build and push both images to the GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - dockerfile: hugo.dockerfile
            image_name: swg-hugo-site
          - dockerfile: data.dockerfile
            image_name: swg-data-builder
        
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set Docker tag
        id: set-tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "tag=prod" >> $GITHUB_OUTPUT;
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=dev" >> $GITHUB_OUTPUT;
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.docker_tag }}" >> $GITHUB_OUTPUT;
          fi

      - name: Set enviroment variable for hugo build command
        id: set-hugo-env-arg
        # 1) If the event is a release, provide version number from git tag
        # 2) If the event is a push to the main branch, provide branch name and sha
        # 3) If the event is a workflow_dispatch:
        #    - If the branch name is release-*, get version number from branch name
        #    - Else provide branch name and sha
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "HUGO_PORTAL_VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT;
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "HUGO_GIT_BRANCH"="main" >> $GITHUB_OUTPUT;
            echo "HUGO_GIT_SHA"=${{ github.sha }} >> $GITHUB_OUTPUT;
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            branch_name="${{ github.ref_name }}"
            if [[ "$branch_name" == release-* ]]; then
              version_number=$(echo "$branch_name" | cut -d '-' -f2)
              echo "HUGO_PORTAL_VERSION=${version_number}" >> $GITHUB_OUTPUT;
            else
              echo "HUGO_GIT_BRANCH"="$branch_name" >> $GITHUB_OUTPUT;
              echo "HUGO_GIT_SHA"=${{ github.sha }} >> $GITHUB_OUTPUT;
            fi
          fi
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          file: ./docker/${{ matrix.dockerfile }}
          tags: ghcr.io/scilifelabdatacentre/${{ matrix.image_name }}:${{ steps.set-tag.outputs.tag }}
          build-args: |
            HUGO_PORTAL_VERSION=${{ steps.set-hugo-env-arg.outputs.HUGO_PORTAL_VERSION }}
            HUGO_GIT_BRANCH=${{ steps.set-hugo-env-arg.outputs.HUGO_GIT_BRANCH }}
            HUGO_GIT_SHA=${{ steps.set-hugo-env-arg.outputs.HUGO_GIT_SHA }}