name: Trivy - Security scan
on:
  push:
    branches:
      - prod # Branch to be deployed in production, through builds tagged prod
      - main # Branch to be deployed in development, through builds tagged dev 
  pull_request:
    branches:
      - prod # Branch to be deployed in production, through builds tagged prod
      - main # Branch to be deployed in development, through builds tagged dev 
  schedule:
    - cron: '15 5 * * 3' # runs at 5:15 AM every Wednesday
    
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
          category: trivy